### ISSUE TITLE
Cannot npm run start main theme in README

### ISSUE THREAD

**Issue by nanjakorewa** [markdumay/hugo-theme-hinode#100]
Thank you for providing a nice hugo theme.
I tried to run the example in the README, but it gave me an error. Attached below is the detailed output. If you know the cause of the problem, I would be happy to get an answer.

Thank you in advance.

#### Environment
- Windows 11 Home (64-bit)
- node version v18.13.0
- hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio

Run all command on Terminal in VSCode

#### Description
For main theme, I could not run npm run start.

```
git clone https://github.com/markdumay/hugo-theme-hinode.git my-hinode-site && cd my-hinode-site
npm install
npm run start
```

```
> @markdumay/hugo-theme-hinode@0.7.8 prestart
> npm run clean


> @markdumay/hugo-theme-hinode@0.7.8 clean
> shx rm -rf public resources


> @markdumay/hugo-theme-hinode@0.7.8 start
> exec-bin node_modules/.bin/hugo/hugo server --bind=0.0.0.0 --disableFastRender

Start building sites …
hugo v0.108.0-a0d64a46e36dd2f503bfd5ba1a5807b900df231d+extended windows/amd64 BuildDate=2022-12-06T13:37:56Z VendorInfo=gohugoio
ERROR 2023/01/10 22:42:41 render of "section" failed: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\_default\list.html:9:28": execute of template failed: template: _default/list.html:9:28: executing "main" at <partial "assets/blog-card.html" $element>: error calling partial: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\partials\assets\blog-card.html:4:16": execute of template failed: template: partials/assets/blog-card.html:4:16: executing "partials/assets/blog-card.html" at <partial "image.html" (dict "url" .Params.thumbnail "ratio" "16x9" "outerClass" "card-img-wrap" "innerClass" "card-img-top" "title" .Params.title)>: error calling partial: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\partials\image.html:26:12": execute of template failed: template: partials/image.html:26:12: executing "partials/image.html" at <partial "utilities/GetImage.html" (dict "url" $url)>: error calling partial: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\partials\utilities\GetImage.html:12:20": execute of template failed: template: partials/utilities/GetImage.html:12:20: executing "partials/utilities/GetImage.html" at <resources.GetMatch>: error calling GetMatch: runtime error: invalid memory address or nil pointer dereference
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: partials/head/head.html:7:7: executing "head" at <partial "head/seo.html" .>: error calling partial: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\partials\head\seo.html:19:18": execute of template failed: template: partials/head/seo.html:19:18: executing "partials/head/seo.html" at <partial "utilities/GetImage.html" (dict "url" .)>: error calling partial: "C:\Users\nanjakorewa-win-ms\workspace\my-hinode-site\layouts\partials\utilities\GetImage.html:12:20": execute of template failed: template: partials/utilities/GetImage.html:12:20: executing "partials/utilities/GetImage.html" at <resources.GetMatch>: error calling GetMatch: runtime error: invalid memory address or nil pointer dereference
Built in 23963 ms
```

I am not familiar with hugo and could not find the detailed cause, but based on the error message, I can see that the error is inside utilities/GetImage.html. Then, it seemed that the `thumbnail: https://picsum.photos/id/184/4288/2848.jpg` line in emoji-support.md was the cause. Then I excluded emoji-support.md and `npm run start` worked fine.

**Comment by markdumay** [comment]
Hi Nanja, thanks for raising this issue! At first glance, I suspect there’s an error with generating the file path when retrieving external images for further processing on Windows. I tested the code on macOS an Linux, but not on Windows yet. 

I’ll run the commands on a Windows system to recreate the problem. Hopefully it’s as simple as using a cross-OS function to define the local file path. Keep you posted.

**Comment by markdumay** [comment]
I created a patch in the branch `image-win` that should fix the issue. Care to test it?

**Comment by nanjakorewa** [comment]
![image](https://user-images.githubusercontent.com/8016471/211773093-fa0b2c0c-7664-4fae-b95a-6251afab2e9a.png)

I was able to build it, thank you so much for the quick fix!

**Comment by markdumay** [comment]
Great! I've merged the changed into the main branch and created a new release `v0.7.9`.
