### ISSUE TITLE
Switcher for language support

### ISSUE THREAD

**Issue by rimatech987** [markdumay/hugo-theme-hinode#56]
Hi Mark,
I was able to create menus and posts in a different language thanks to i18n support, but I don't see any drop-down menus to help me switch between languages like in **Blist**. 
Can you add it? Have you planned to complete this feature?

Thanks :smile:

**Comment by rimatech987** [comment]
Any news here @markdumay ?

**Comment by markdumay** [comment]
I added a new branch called `language`. The site should now support multiple languages and show a drop-down selector in the navigation bar when appropriate. Looking forward to your feedback!

**Comment by markdumay** [comment]
I merged the changes into a new release with version `0.6.0`. Let me know if it works as expected!

**Comment by rimatech987** [comment]
From early tests, it seems to work well. Great :smile:

**Comment by markdumay** [comment]
Great! Let me know if you do encounter any issues. On 8 Dec 2022, at 13:09, rimatech987 ***@***.***> wrote:﻿
From early tests, it seems to work well. Great 😄
